### ISSUE TITLE
Exception on quit (while offlineimap is importing mail from Gmail)

### ISSUE THREAD

**Issue by jkakar** [sup-heliotrope/sup#436] opened 2015-05-30 03:43 UTC
I was running an import of mail from Gmail with offline IMAP and I
opened sup.  I could see mail streaming into the inbox quit quickly.
On exit I got an exception (which I've not been able to reproduce on a
second load/quit attempt):

```
--- NoMethodError from thread: poll after loading inbox
undefined method `<<' for nil:NilClass
(eval):1:in `<<'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:210:in `block (2 levels) in poll_from'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:210:in `block in poll_from'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:161:in `block in poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each_with_index'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:201:in `poll_from'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:136:in `each'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:136:in `block in do_poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:135:in `synchronize'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:135:in `do_poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/modes/poll_mode.rb:15:in `poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:58:in `poll_with_sources'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:94:in `poll'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/bin/sup:208:in `block (2 levels) in <module:Redwood>'
/Users/jkakar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sup-0.21.0/lib/sup.rb:88:in `block in reporting_thread'
```

**Comment by gauteh** [comment] 2015-05-30 08:06
probably duplicate of #372.

**Closed** 2015-06-01 06:10 UTC
Labels: duplicate
