### ISSUE TITLE
ERROR: oh crap, an exception

### ISSUE THREAD

**Issue by bfronhoefer** [sup-heliotrope/sup#587] opened 2020-12-15 13:47 UTC
I installed sup according to 
https://github.com/sup-heliotrope/sup/wiki/Installation%3A-Archlinux
ran sup-config, sup, sup-sync and sup again.
An error occurred and I was asked to report it.

$HOME/.sup/exception-log.txt
--- Psych::SyntaxError from thread: main
(/home/bf/.sup/sources.yaml): did not find expected whitespace or line break while scanning a tag at line 2 column 3
/usr/lib/ruby/2.7.0/psych.rb:456:in `parse'
/usr/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
/usr/lib/ruby/2.7.0/psych.rb:390:in `parse'
/usr/lib/ruby/2.7.0/psych.rb:277:in `load'
/usr/lib/ruby/2.7.0/psych.rb:578:in `block in load_file'
/usr/lib/ruby/2.7.0/psych.rb:577:in `open'
/usr/lib/ruby/2.7.0/psych.rb:577:in `load_file'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/lib/sup.rb:145:in `load_yaml_obj'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/lib/sup/source.rb:227:in `load_sources'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/lib/sup/index.rb:102:in `load'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/lib/sup/util.rb:605:in `method_missing'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/bin/sup:146:in `<module:Redwood>'
/home/bf/.gem/ruby/2.7.0/gems/sup-1.0/bin/sup:76:in `<top (required)>'
/home/bf/.gem/ruby/2.7.0/bin/sup:23:in `load'
/home/bf/.gem/ruby/2.7.0/bin/sup:23:in `<main>'

**Comment by thomasmatecki** [comment] 2021-04-01 02:36
Looks like a duplicate of #577

**Closed** 2022-04-17 08:26 UTC
Labels: duplicate
