### ISSUE TITLE
Sup no longer loading mails, crashes on key press

### ISSUE THREAD

**Issue by TyberiusPrime** [sup-heliotrope/sup#476] opened 2015-09-21 07:53 UTC
Hello,
my sup crashed, now it doesn't start up again,
it just sits there, saying 'Searching for threads...' without consuming cpu,
and crashes when I press for example page-down, page-up, 'a', or start a new search.

sup-sync did not help :(

Exception log:

--- RuntimeError from thread: load threads for thread-index-mode

/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:630:in `get_entry'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:639:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:236:in `build_message'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:165:in `block (2 levels) in each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/thread.rb:344:in `call'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/thread.rb:344:in `block in load_n_threads'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:165:in `block in each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:288:in `block in each_id'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:288:in `each'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:288:in `each_id'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/index.rb:165:in `each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/thread.rb:340:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/var/lib/gems/2.1.0/gems/sup-0.22.1/lib/sup.rb:87:in `block in reporting_thread'

**Comment by TyberiusPrime** [comment] 2015-09-24 08:37
the @flush_id fix from #473 does not help.

**Comment by gauteh** [comment] 2015-09-24 19:19
Duplicate of: #372.

**Closed by gauteh** 2015-09-24 19:19 UTC
Labels: bug, duplicate
