### ISSUE TITLE
ERROR: oh crap, an exception

### ISSUE THREAD

**Issue by Aurora-Aureus** [sup-heliotrope/sup#594] opened 2021-08-18 22:12 UTC
so I've just tried setting up sup and it kinda broke, I followed the  Complete gmail configuration, I copy-pasted the .offlineimaprc file, but had to remove status_backend = sqlite, since it said it was deprecated, also removed folderfilter = lambda folder: folder == '[Gmail]/All Mail' since it said that there may be a folderfilter issue and didn't run.
Now offlineimap finally did run and at the end I just launched sup, it didn't start and I was confronted with an apology saying that I should submit a report of the error
here's the exception-log.txt
[exception-log.txt](https://github.com/sup-heliotrope/sup/files/7010481/exception-log.txt)

I'm very sorry for any inconvenience I'm causing. Whoever reads this, have a great day!

**Comment by danc86** [comment] 2022-04-17 08:45
Thanks for the report. This is a dupe of #577 (now fixed).

**Comment by danc86** [comment] 2022-04-17 08:46
Sorry, wrong number. I meant, dupe of #588.

**Closed by danc86** 2022-04-17 08:45 UTC
Labels: duplicate
